services:

  flux_se.sylius_payum_stripe.form.type.gateway_configuration.stripe_checkout_session:
    class: FluxSE\SyliusPayumStripePlugin\Form\Type\StripeGatewayConfigurationType
    tags:
      - name: sylius.gateway_configuration_type
        type: stripe_checkout_session
        label: flux_se_sylius_payum_stripe_plugin.payum_gateway_factory.stripe_checkout_session
      - name: form.type
